### PR TITLE
I'm trying, and I fixed indentation. Files won't read correctly

### PR DESCRIPTION
**Pull request by Unown256**
I've tried, but the files reading hates me

### CODE REVIEW

**Comment by Unown256** [comment]
I got it to print the text but it's path is the path straight from the C: drive on my PC

**Comment by AdrianTwo** [comment]
Okay, thank you for helping

**Comment by AdrianTwo** [comment]
Maybe it works now, I changed some issues. If it doesent work, what error do you get?

**Comment by AdrianTwo** [comment]
Oh yeah, that’s probably because of your ide. You have to execute the python script from your console.

**Pull request merged**
